"""add supabase_id to users

Revision ID: 06522abaaaaa
Revises: c3a1f8b92d47
Create Date: 2026-04-05 17:17:04.088765
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06522abaaaaa'
down_revision: Union[str, None] = 'c3a1f8b92d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('essay_feedback',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('essay_id', sa.UUID(), nullable=False),
    sa.Column('signal', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['essay_id'], ['essays.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_essay_feedback_essay_id'), 'essay_feedback', ['essay_id'], unique=False)
    op.create_index(op.f('ix_essay_feedback_user_id'), 'essay_feedback', ['user_id'], unique=False)
    op.add_column('users', sa.Column('supabase_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_supabase_id'), 'users', ['supabase_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_supabase_id'), table_name='users')
    op.drop_column('users', 'supabase_id')
    op.drop_index(op.f('ix_essay_feedback_user_id'), table_name='essay_feedback')
    op.drop_index(op.f('ix_essay_feedback_essay_id'), table_name='essay_feedback')
    op.drop_table('essay_feedback')
    # ### end Alembic commands ###
