"""add topic_history table

Revision ID: 129fd5f7678e
Revises: 06522abaaaaa
Create Date: 2026-04-05 20:32:13.728396
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '129fd5f7678e'
down_revision: Union[str, None] = '06522abaaaaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_history',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('sub_domain', sa.String(length=255), nullable=True),
    sa.Column('angle', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_history_user_id'), 'topic_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_history_user_id'), table_name='topic_history')
    op.drop_table('topic_history')
    # ### end Alembic commands ###
