"""add length_tier to essays

Revision ID: bf2c37a51633
Revises: b7da46eafd46
Create Date: 2026-03-17 23:17:47.717340
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf2c37a51633'
down_revision: Union[str, None] = 'b7da46eafd46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('essays', sa.Column('length_tier', sa.String(length=20), server_default='deep_dive', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('essays', 'length_tier')
    # ### end Alembic commands ###
