"""Interest → sub-domain mapping for topic diversity.

Each broad interest maps to 8-12 specific sub-domains. The pipeline
rotates through sub-domains so the same one isn't reused until all
others have been visited.
"""

SUBDOMAIN_MAP: dict[str, list[str]] = {
    "Philosophy": [
        "philosophy of mind",
        "ethics of technology",
        "epistemology",
        "existentialism",
        "political philosophy",
        "logic and paradoxes",
        "philosophy of language",
        "aesthetics",
        "metaphysics",
        "philosophy of science",
        "phenomenology",
        "philosophy of mathematics",
    ],
    "Cognitive Science": [
        "embodied cognition",
        "computational neuroscience",
        "decision-making under uncertainty",
        "language acquisition",
        "cognitive development",
        "attention and perception",
        "memory systems",
        "cognitive anthropology",
        "animal cognition",
        "metacognition",
        "spatial reasoning",
    ],
    "AI & Machine Learning": [
        "reinforcement learning",
        "interpretability and explainability",
        "AI safety and alignment",
        "natural language understanding",
        "generative models",
        "robotics and embodied AI",
        "computational creativity",
        "federated learning",
        "AI ethics and governance",
        "neuro-symbolic AI",
        "multi-agent systems",
        "AI in scientific discovery",
    ],
    "Economics": [
        "behavioral economics",
        "development economics",
        "institutional economics",
        "monetary theory",
        "labor economics",
        "environmental economics",
        "economic history",
        "game theory applications",
        "public choice theory",
        "economics of innovation",
        "informal economies",
    ],
    "History": [
        "counterfactual history",
        "history of science and technology",
        "social history",
        "military history",
        "economic history",
        "history of ideas",
        "colonial and postcolonial history",
        "environmental history",
        "microhistory",
        "history of everyday life",
        "maritime history",
        "oral history traditions",
    ],
    "Psychology": [
        "neuropsychology",
        "forensic psychology",
        "health psychology",
        "developmental psychology",
        "cross-cultural psychology",
        "sports psychology",
        "evolutionary psychology",
        "social psychology",
        "positive psychology",
        "industrial-organizational psychology",
        "psycholinguistics",
        "psychology of creativity",
    ],
    "Physics": [
        "quantum information",
        "condensed matter physics",
        "cosmology and dark matter",
        "plasma physics",
        "biophysics",
        "statistical mechanics",
        "particle physics",
        "astrophysics",
        "nonlinear dynamics and chaos",
        "nuclear physics",
        "physics of complex systems",
        "history of physics",
    ],
    "Literature": [
        "narrative theory",
        "comparative literature",
        "postcolonial literature",
        "literary translation",
        "genre fiction studies",
        "oral literature and storytelling",
        "literary criticism and theory",
        "literature and philosophy",
        "censorship and banned books",
        "experimental fiction",
        "literature of exile and diaspora",
        "ecocriticism",
    ],
    "Neuroscience": [
        "consciousness studies",
        "neuroplasticity",
        "neuroethics",
        "sensory neuroscience",
        "social neuroscience",
        "computational neuroscience",
        "neuroscience of sleep and dreams",
        "neuropharmacology",
        "motor neuroscience",
        "neuroscience of pain",
        "neuroscience of music",
        "developmental neuroscience",
    ],
    "Political Theory": [
        "democratic theory",
        "anarchism and libertarianism",
        "theories of justice",
        "feminist political theory",
        "postcolonial political thought",
        "sovereignty and the state",
        "political economy",
        "deliberative democracy",
        "biopolitics",
        "theories of revolution",
        "environmental political theory",
        "political theology",
    ],
    "Sociology": [
        "sociology of knowledge",
        "urban sociology",
        "sociology of religion",
        "medical sociology",
        "sociology of emotions",
        "digital sociology",
        "sociology of organizations",
        "sociology of deviance",
        "economic sociology",
        "sociology of science",
        "migration studies",
        "cultural sociology",
    ],
    "Mathematics": [
        "number theory",
        "topology",
        "combinatorics",
        "mathematical logic",
        "probability theory",
        "dynamical systems",
        "graph theory",
        "cryptography",
        "history of mathematics",
        "mathematical philosophy",
        "category theory",
        "computational complexity",
    ],
    "Biology & Evolution": [
        "evolutionary developmental biology",
        "microbiology and microbiomes",
        "conservation biology",
        "behavioral ecology",
        "paleobiology",
        "synthetic biology",
        "epigenetics",
        "marine biology",
        "parasitology",
        "plant intelligence",
        "extremophile biology",
        "biomimicry",
    ],
    "Art & Design": [
        "design philosophy",
        "art and technology",
        "history of color",
        "architecture and space",
        "typography and lettering",
        "land art and environmental art",
        "outsider art and art brut",
        "design for accessibility",
        "art forgery and authentication",
        "kinetic and interactive art",
        "indigenous art traditions",
        "art and politics",
    ],
    "Technology": [
        "distributed systems",
        "human-computer interaction",
        "privacy and surveillance tech",
        "open source culture",
        "history of computing",
        "internet infrastructure",
        "programming language theory",
        "digital preservation",
        "assistive technology",
        "technology and labor",
        "edge computing",
        "quantum computing",
    ],
    "Linguistics": [
        "historical linguistics",
        "sociolinguistics",
        "psycholinguistics",
        "computational linguistics",
        "phonology and phonetics",
        "language endangerment",
        "sign language linguistics",
        "pragmatics and discourse",
        "morphology and syntax",
        "forensic linguistics",
        "language and thought",
        "writing systems",
    ],
    "Climate & Environment": [
        "climate modeling",
        "environmental justice",
        "ocean science and acidification",
        "renewable energy systems",
        "biodiversity loss",
        "indigenous environmental knowledge",
        "geoengineering",
        "urban ecology",
        "soil science and carbon",
        "water systems and scarcity",
        "environmental ethics",
        "climate adaptation strategies",
    ],
    "Space & Astronomy": [
        "exoplanet science",
        "astrobiology",
        "space policy and governance",
        "stellar evolution",
        "gravitational wave astronomy",
        "planetary geology",
        "space archaeology",
        "radio astronomy",
        "history of space exploration",
        "interstellar medium",
        "near-earth objects",
        "space habitat design",
    ],
}


def get_subdomains(interest: str) -> list[str]:
    """Return sub-domains for an interest, with fuzzy matching fallback."""
    # Exact match
    if interest in SUBDOMAIN_MAP:
        return SUBDOMAIN_MAP[interest]

    # Case-insensitive match
    lower = interest.lower()
    for key, val in SUBDOMAIN_MAP.items():
        if key.lower() == lower:
            return val

    # Substring match (e.g., "AI" matches "AI & Machine Learning")
    for key, val in SUBDOMAIN_MAP.items():
        if lower in key.lower() or key.lower() in lower:
            return val

    # No match — return empty (pipeline will use the interest as-is)
    return []
